#!/bin/bash

yacjson_build() {
  target=yacjson.h
  echo -n > $target
  for file in arraylist.h hashmap.h yacjson-core.h; do
      cat $file >> $target
      echo "" >> $target
  done
  echo -e "#ifdef YACJSON_IMPLEMENTATION\n" >> $target
  for file in arraylist.c hashmap.c yacjson-core.c; do
      cat $file >> $target
      echo "" >> $target
  done
  echo "#endif" >> $target
  grep -v -E '#include "arraylist.h"|#include "hashmap.h"|#include "yacjson-core.h"' $target > $target.bak
  cat $target.bak > $target
  rm -f $target.bak
}

yacjson_build()
